version: "3.9"

services:
  ingest:
    build:
      context: .
      dockerfile: docker/Dockerfile.ingest
    container_name: ingest_container
    volumes:
      - ./data/raw:/app/raw
      - ./data/samples:/app/samples   # optionnel, pour tests
    networks:
      - ml-network

  etl:
    build:
      context: .
      dockerfile: docker/Dockerfile.etl
    container_name: etl_container
    volumes:
      - ./data/raw:/app/raw
      - ./data/processed:/app/processed
      - ./data/samples:/app/samples   # optionnel, pour tests
    depends_on:
      - ingest
    networks:
      - ml-network

  training:
    build:
      context: .
      dockerfile: docker/Dockerfile.training
    container_name: training_container
    volumes:
      - ./data/processed:/app/processed
      - ./data/models:/app/models
    depends_on:
      - etl
    networks:
      - ml-network

  front:
    build:
      context: .
      dockerfile: docker/Dockerfile.front
    container_name: front_container
    ports:
      - "8501:8501"   # ex: Streamlit
    volumes:
      - ./data/processed:/app/processed
      - ./data/models:/app/models
    depends_on:
      - etl
      - training
    networks:
      - ml-network

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: always
    depends_on:
      - ingest
      - etl
      - training
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge
